/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mkr_MkrMsgBox */

#ifndef _Included_com_mkr_MkrMsgBox
#define _Included_com_mkr_MkrMsgBox
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mkr_MkrMsgBox_MKR_MSG_BOX_RES_CANCEL
#define com_mkr_MkrMsgBox_MKR_MSG_BOX_RES_CANCEL 0L
#undef com_mkr_MkrMsgBox_MKR_MSG_BOX_RES_OK
#define com_mkr_MkrMsgBox_MKR_MSG_BOX_RES_OK 1L
/*
 * Class:     com_mkr_MkrMsgBox
 * Method:    InitMsgBoxNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkrMsgBox_InitMsgBoxNTV
  (JNIEnv *, jobject);

/*
 * Class:     com_mkr_MkrMsgBox
 * Method:    MsgBoxCallbackNTV
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkrMsgBox_MsgBoxCallbackNTV
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_mkr_MkrMsgBox_MsgBoxOnClick */

#ifndef _Included_fcnavgl_nintf_MkrMsgBox_MsgBoxOnClick
#define _Included_fcnavgl_nintf_MkrMsgBox_MsgBoxOnClick
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
