/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_mkrnav_MkRlNativeManager */

#ifndef _Included_net_mkrnav_MkRlNativeManager
#define _Included_net_mkrnav_MkRlNativeManager
#ifdef __cplusplus
extern "C" {
#endif
#undef net_mkrnav_MkRlNativeManager_NATIVE_THREAD_PRIORITY
#define net_mkrnav_MkRlNativeManager_NATIVE_THREAD_PRIORITY -18L
#undef net_mkrnav_MkRlNativeManager_CAMERA_PREVIEW_TIMEOUT
#define net_mkrnav_MkRlNativeManager_CAMERA_PREVIEW_TIMEOUT 60000LL
#undef net_mkrnav_MkRlNativeManager_WAZE_WIDGET_ENABLED
#define net_mkrnav_MkRlNativeManager_WAZE_WIDGET_ENABLED 0L
#undef net_mkrnav_MkRlNativeManager_MEMORY_PROFILER_ENABLED
#define net_mkrnav_MkRlNativeManager_MEMORY_PROFILER_ENABLED 1L
#undef net_mkrnav_MkRlNativeManager_CPU_PROFILER_ENABLED
#define net_mkrnav_MkRlNativeManager_CPU_PROFILER_ENABLED 1L
#undef net_mkrnav_MkRlNativeManager_TEMPERATURE_PROFILER_ENABLED
#define net_mkrnav_MkRlNativeManager_TEMPERATURE_PROFILER_ENABLED 0L
#undef net_mkrnav_MkRlNativeManager_MEMORY_PROFILER_PERIOD
#define net_mkrnav_MkRlNativeManager_MEMORY_PROFILER_PERIOD 600000LL
#undef net_mkrnav_MkRlNativeManager_TEMPERATURE_PROFILER_PERIOD
#define net_mkrnav_MkRlNativeManager_TEMPERATURE_PROFILER_PERIOD 120000LL
#undef net_mkrnav_MkRlNativeManager_STORAGE_SPACE_LOW_BOUND
#define net_mkrnav_MkRlNativeManager_STORAGE_SPACE_LOW_BOUND 5000000LL

	
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_createAssetManager
(JNIEnv* env, jobject aJObj, jobject assetManager);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    UrlHandlerNTV
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_UrlHandlerNTV
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    NativeMsgDispatcherNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_NativeMsgDispatcherNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    InitNativeManagerNTV
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_InitNativeManagerNTV
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    AppStartNTV
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_AppStartNTV
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    AppShutDownNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_AppShutDownNTV
  (JNIEnv *, jobject);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    ShowGpsDisabledWarningNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_ShowGpsDisabledWarningNTV
  (JNIEnv *, jobject);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    BackLightMonitorResetNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_BackLightMonitorResetNTV
  (JNIEnv *, jobject);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    SetUpgradeRunNTV
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_SetUpgradeRunNTV
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    SetBackgroundRunNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_SetBackgroundRunNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    EditBoxCallbackNTV
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_EditBoxCallbackNTV
  (JNIEnv *, jobject, jint, jstring, jlong);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    TakePictureCallbackNTV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_TakePictureCallbackNTV
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    EditBoxCheckTypingLockNTV
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_EditBoxCheckTypingLockNTV
  (JNIEnv *, jobject);

/*
 * Class:     net_mkrnav_MkRlNativeManager
 * Method:    ConnectivityChangedNTV
 * Signature: (ZILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeManager_ConnectivityChangedNTV
  (JNIEnv *, jobject, jboolean, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlNativeManager_CheckSDCardCallback */

#ifndef _Included_net_mkrnav_MkRlNativeManager_CheckSDCardCallback
#define _Included_net_mkrnav_MkRlNativeManager_CheckSDCardCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlNativeManager_CompatabilityWrapper */

#ifndef _Included_net_mkrnav_MkRlNativeManager_CompatabilityWrapper
#define _Included_net_mkrnav_MkRlNativeManager_CompatabilityWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlNativeManager_FreeMapUIEvent */

#ifndef _Included_net_mkrnav_MkRlNativeManager_FreeMapUIEvent
#define _Included_net_mkrnav_MkRlNativeManager_FreeMapUIEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlNativeManager_FreeMapUIMsgDispatcher */

#ifndef _Included_net_mkrnav_MkRlNativeManager_FreeMapUIMsgDispatcher
#define _Included_net_mkrnav_MkRlNativeManager_FreeMapUIMsgDispatcher
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlNativeManager_NativeThread */

#ifndef _Included_net_mkrnav_MkRlNativeManager_NativeThread
#define _Included_net_mkrnav_MkRlNativeManager_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
