/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mkrnavgl_nintf_MkrNativeTimerManager */

#ifndef _Included_com_mkrnavgl_nintf_MkrNativeTimerManager
#define _Included_com_mkrnavgl_nintf_MkrNativeTimerManager
#ifdef __cplusplus
extern "C" {
#endif
#undef net_mkrnav_MkRlNativeTimerManager_MKR_MAX_TASK_COUNT
#define net_mkrnav_MkRlNativeTimerManager_MKR_MAX_TASK_COUNT 32L
/*
 * Class:     com_mkrnavgl_nintf_MkrNativeTimerManager
 * Method:    InitTimerManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlNativeTimerManager_InitTimerManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
