/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waze_MkRlSoundManager */

#ifndef _Included_net_mkrnav_MkRlSoundManager
#define _Included_net_mkrnav_MkRlSoundManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_MkRlSoundManager_SOUND_BUFFERING_ENABLED
#define com_waze_MkRlSoundManager_SOUND_BUFFERING_ENABLED 0L
/*
 * Class:     com_waze_MkRlSoundManager
 * Method:    InitSoundManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlSoundManager_InitSoundManagerNTV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_MkRlSoundManager_MkrAudioPlayer */

#ifndef _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer
#define _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_waze_MkRlSoundManager_MkrAudioPlayer_MIN_PRIORITY
#define com_waze_MkRlSoundManager_MkrAudioPlayer_MIN_PRIORITY 1L
#undef com_waze_MkRlSoundManager_MkrAudioPlayer_NORM_PRIORITY
#define com_waze_MkRlSoundManager_MkrAudioPlayer_NORM_PRIORITY 5L
#undef com_waze_MkRlSoundManager_MkrAudioPlayer_MAX_PRIORITY
#define com_waze_MkRlSoundManager_MkrAudioPlayer_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_MkRlSoundManager_MkrAudioPlayer_CompletionListener */

#ifndef _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer_CompletionListener
#define _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer_CompletionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_waze_MkRlSoundManager_MkrAudioPlayer_ErrorListener */

#ifndef _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer_ErrorListener
#define _Included_net_mkrnav_MkRlSoundManager_MkrAudioPlayer_ErrorListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
