/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_mkrnav_MkRlTtsManager */

#ifndef _Included_net_mkrnav_MkRlTtsManager
#define _Included_net_mkrnav_MkRlTtsManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_mkrnav_MkRlTtsManager
 * Method:    InitTtsManagerNTV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlTtsManager_InitTtsManagerNTV
  (JNIEnv *, jobject);

/*
 * Class:     net_mkrnav_MkRlTtsManager
 * Method:    TtsManagerCallbackNTV
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_mkr_navgl_service_MkRlTtsManager_TtsManagerCallbackNTV
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_mkrnav_MkRlTtsManager_UtteranceCompletedListener */

#ifndef _Included_net_mkrnav_MkRlTtsManager_UtteranceCompletedListener
#define _Included_net_mkrnav_MkRlTtsManager_UtteranceCompletedListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
