/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "JuceHeader.h"
#include "MainAppWindow.h"



//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (JUCE_Mkr_MobileApplication)
